export type AggregateFunction =
  // General-Purpose Aggregate Functions
  // https://www.postgresql.org/docs/current/functions-aggregate.html#FUNCTIONS-AGGREGATE-TABLE
  | "ANY_VALUE"
  | "ARRAY_AGG"
  | "AVG"
  | "BIT_AND"
  | "BIT_OR"
  | "BIT_XOR"
  | "BOOL_AND"
  | "BOOL_OR"
  | "COUNT"
  | "EVERY"
  | "JSON_AGG_STRICT"
  | "JSON_AGG"
  | "JSON_OBJECT_AGG_STRICT"
  | "JSON_OBJECT_AGG_UNIQUE_STRICT"
  | "JSON_OBJECT_AGG_UNIQUE"
  | "JSON_OBJECT_AGG"
  | "JSONB_AGG_STRICT"
  | "JSONB_AGG"
  | "JSONB_OBJECT_AGG_STRICT"
  | "JSONB_OBJECT_AGG_UNIQUE_STRICT"
  | "JSONB_OBJECT_AGG_UNIQUE"
  | "JSONB_OBJECT_AGG"
  | "MAX"
  | "MIN"
  | "RANGE_AGG"
  | "RANGE_INTERSECT_AGG"
  | "STRING_AGG"
  | "SUM"
  | "XMLAGG"

  // Aggregate Functions for Statistics
  // https://www.postgresql.org/docs/current/functions-aggregate.html#FUNCTIONS-AGGREGATE-STATISTICS-TABLE
  | "CORR"
  | "COVAR_POP"
  | "COVAR_SAMP"
  | "REGR_AVGX"
  | "REGR_AVGY"
  | "REGR_COUNT"
  | "REGR_INTERCEPT"
  | "REGR_R2"
  | "REGR_SLOPE"
  | "REGR_SXX"
  | "REGR_SXY"
  | "REGR_SYY"
  | "STDDEV_POP"
  | "STDDEV_SAMP"
  | "STDDEV"
  | "VAR_POP"
  | "VAR_SAMP"
  | "VARIANCE"

  // Custom Aggregate Functions
  | (string & {});
